### ISSUE TITLE
打开后出错

### ISSUE THREAD

**Issue by noncharacter** [XDawned/FTBQLocalizationTools#10]
https://pste.ch/odexiyewob.rb
是full版。
![pic](https://github.com/XDawned/FTBQLocalizationTools/assets/19724779/48373a9f-67bf-4cfb-993d-8db9168d57ca)
是创建不了这个文件还是？
之前用api版翻译了约27万字符后直接闪退了，才改用full

**Comment by XDawned** [comment]
解决方案见 #8 最新评论
