### ISSUE TITLE
控制台报错打不开

### ISSUE THREAD

**Issue by WQMYH** [XDawned/FTBQLocalizationTools#11]
![image](https://github.com/XDawned/FTBQLocalizationTools/assets/138088516/40cb8d35-73a9-4980-bc1d-30d1725f1e10)

**Comment by XDawned** [comment]
感谢反馈

与 https://github.com/XDawned/FTBQLocalizationTools/issues/8 相同，出现ConnectionResetError与离线模型托管站点网络不稳定有关
目前可以暂时使用精简版，采用[百度翻译API](http://api.fanyi.baidu.com/)作为翻译源，你可以在[这里](https://fanyi-api.baidu.com/?fr=pcHeader)申请

后面我会尝试在新版本修复,你可以加入介绍此项目的视频简介下方的qq群，参与新版本内测。

**Comment by WQMYH** [comment]
我免费额度已经用完了好像😀群号能发一下嘛？我从别的up那知道的😂

**Comment by XDawned** [comment]
解决方案见 #8 最新评论
