### ISSUE TITLE
1.12ftb任务提取本地化键问题

### ISSUE THREAD

**Issue by nageih** [XDawned/FTBQLocalizationTools#13]
用的rad1.53版本整合包测试，1.12会有以text为key的任务文本，无法提取
![image](https://github.com/XDawned/FTBQLocalizationTools/assets/102042030/23f854a1-5072-466e-9621-11624beaf541)

**Comment by XDawned** [comment]
[v1.4.1](https://github.com/XDawned/FTBQLocalizationTools/releases/tag/v1.4.1)更新已修复
如果使用后问题解决请关闭此issue
