### ISSUE TITLE
精简版

### ISSUE THREAD

**Issue by nageih** [XDawned/FTBQLocalizationTools#14]
是否可以出一个只能提取任务本地化key的精简版，目前的版本有太多功能用不上，启动还下载一堆东西，体积还很大

**Comment by Blackwithking** [comment]
可以使用https://github.com/XDawned/FTBQLocalizationTools/releases/tag/v1.2
中的8 MB左右的版本，此版本是使用api翻译（大概率用不上api的机翻），用来提取snbt速度很快


另外，给作者一个建议：将翻译的模型之类的杂七杂八的文件放一个文件夹里，单独保留出exe文件、输入输出文件夹

**Comment by XDawned** [comment]
已更新
[v1.4.2-MINI](https://github.com/XDawned/FTBQLocalizationTools/releases/tag/v1.4.2)
