### ISSUE TITLE
snbt任务提取出现错误，导致文件失效

### ISSUE THREAD

**Issue by Blackwithking** [XDawned/FTBQLocalizationTools#15]
整合包为The-Decursio-Project-Expert-1.0.5，其原始版本任务都能正常显示，但用FTB小工具的1.2的api版本提取任务键名时会出现括号错误，导致多个任务在文件中被识别为一个任务
部分可看：https://github.com/VM-Chinese-translate-group/The-Decursio-Project-Expert-chinese-patch/commit/d618e3e44981a013eb93d189de843a636af5d1e0

**Comment by XDawned** [comment]
已定位到原因并找出解决方案，后续上层lib库更新后会同步在下个版本修复
https://github.com/Tryanks/python-snbtlib/issues/11

**Comment by XDawned** [comment]
> 已定位到原因并找出解决方案，后续上层lib库更新后会同步在下个版本修复 [Tryanks/python-snbtlib#11](https://github.com/Tryanks/python-snbtlib/issues/11)

已修复
