### ISSUE TITLE
1.12严重问题

### ISSUE THREAD

**Issue by nageih** [XDawned/FTBQLocalizationTools#16]
提取后任务文件snbt格式会变，导致完全加载不出来任务
提取前：
![提取前](https://github.com/XDawned/FTBQLocalizationTools/assets/102042030/5cb85f2f-a694-419e-9a95-4963e1f9d6e1)
提取后：
![提取后](https://github.com/XDawned/FTBQLocalizationTools/assets/102042030/073a67b1-2eb5-4658-8712-a4547de340b3)

还有就是index.snbt格式也变了，猜测是snbtlib的问题

**Comment by XDawned** [comment]
这里主要是由于行末`,`缺失引起的，在高版本行末逗号被取消了，正式引用这种变动的节点是1.12.2，所以导致在1.12.2一个版本下存在末尾有逗号与无逗号的两种格式，此问题在此脚本最新版本已修复。
