### ISSUE TITLE
[非建议/反馈] 原来还有这种思路

### ISSUE THREAD

**Issue by Tryanks** [XDawned/FTBQLocalizationTools#3]
我之前写类似东西的时候直接生造了个SNBT Reader（（
https://pypi.org/project/snbtlib/

**Comment by XDawned** [comment]
感谢您的轮子，后面代码中我将会使用此库，专注于ftbquests内部格式处理
同时使用此库时遇到了一些bug，已反馈至您的gmail邮箱

**Comment by Tryanks** [comment]
> 感谢您的轮子，后面代码中我将会使用此库，专注于ftbquests内部格式处理 同时使用此库时遇到了一些bug，已反馈至您的gmail邮箱

注意到这条回复已经是一周后，很抱歉但是我完全不看gmail邮箱的，它只是客观存在。我的常用邮箱是tryanks@outlook.com。
我会去gmail看一下您的反馈的，非常感谢。

**Comment by LinHeLurking** [comment]
注意到 reddit 上有这样一个教程 https://www.reddit.com/r/feedthebeast/comments/qllnpq/how_to_translate_quests_in_a_modpack_and_my/
利用 kubejs 可以给 ftb quests 做国际化。我想是否可以利用这个脚本自动生成 translation key，然后输出相应的语言文件。这样可能也更加方便校验一点。

**Comment by XDawned** [comment]
> 注意到 reddit 上有这样一个教程 https://www.reddit.com/r/feedthebeast/comments/qllnpq/how_to_translate_quests_in_a_modpack_and_my/ 利用 kubejs 可以给 ftb quests 做国际化。我想是否可以利用这个脚本自动生成 translation key，然后输出相应的语言文件。这样可能也更加方便校验一点。

感谢您的建议，我也对此刚好也有一些打算，还在尝试中。
其具体是额外提供一种机翻方式，生成原语言键值表后再机翻生成汉化zh_cn.json以方便后期人工修正，当然也可单独的当作一个本地化键工具使用，而不调用翻译...

另外已经有mod实现了FTB任务本地化键，目前你可以将此脚本处理生成的机翻再通过此mod进行转化，[FTB Quests: Localization keys](https://www.mcmod.cn/class/7244.html)

**Comment by LinHeLurking** [comment]
> > 注意到 reddit 上有这样一个教程 https://www.reddit.com/r/feedthebeast/comments/qllnpq/how_to_translate_quests_in_a_modpack_and_my/ 利用 kubejs 可以给 ftb quests 做国际化。我想是否可以利用这个脚本自动生成 translation key，然后输出相应的语言文件。这样可能也更加方便校验一点。
> 
> 感谢您的建议，我也对此刚好也有一些打算，还在尝试中。 其具体是额外提供一种机翻方式，生成原语言键值表后再机翻生成汉化zh_cn.json以方便后期人工修正，当然也可单独的当作一个本地化键工具使用，而不调用翻译...
> 
> 另外已经有mod实现了FTB任务本地化键，目前你可以将此脚本处理生成的机翻再通过此mod进行转化，[FTB Quests: Localization keys](https://www.mcmod.cn/class/7244.html)

我也在做类似的工具，正在抄 FTB 读 SNBT 文件的实现然后转 JSON。你说的那个 mod 我也看到了，但是一方面我觉得这玩意用 mod 就很不方便，另一方面这个 mod 很久没更新了。
