### ISSUE TITLE
这个工具的教程并不能让此工具正常运行

### ISSUE THREAD

**Issue by KlparetlR** [XDawned/FTBQLocalizationTools#4]
![截图20230312174704](https://user-images.githubusercontent.com/105189905/224536882-bae84521-108a-4a87-9617-3c6e5ec8e19f.png)

**Comment by XDawned** [comment]
感谢反馈
由于我先前的发布中库文件缺少了正则解析导致找不到引入文件，现已补全上传。

**Comment by KlparetlR** [comment]
![20230314110953](https://user-images.githubusercontent.com/105189905/224883244-1d101624-9fcc-4b89-8d39-78ec61d49da1.png)

**Comment by KlparetlR** [comment]
这个是要去哪下什么吗？

**Comment by KlparetlR** [comment]
![截图20230314111246](https://user-images.githubusercontent.com/105189905/224883642-be8f6310-a593-45b8-b7a5-76946efe61ae.png)

**Comment by KlparetlR** [comment]
![截图20230314111334](https://user-images.githubusercontent.com/105189905/224883753-09c0255a-7582-492c-b9f1-a09683f9e9db.png)

**Comment by XDawned** [comment]
更新项目后，你可以尝试在Python控制台执行pip install requests和pip install snbtlib手动安装这些外部库（一般你的开发工具会提醒或自动帮你下载这些外部库）

**Comment by KlparetlR** [comment]
那你最好在教程里补上，我在CFPA看见你们发的，几个月后才想起来

**Comment by KlparetlR** [comment]
还有，你可以加个功能，把机翻支持一下lang，有些整合包作者的FTB任务已经lang化了（使用Textrue的移植模组https://modrinth.com/mod/re-ftbqkeys ）

**Comment by KlparetlR** [comment]
> 更新项目后，你可以尝试在Python控制台执行pip install requests和pip install snbtlib手动安装这些外部库（一般你的开发工具会提醒或自动帮你下载这些外部库）

你关的太快了

**Comment by XDawned** [comment]
> 还有，你可以加个功能，把机翻支持一下lang，有些整合包作者的FTB任务已经lang化了（使用Textrue的移植模组https://modrinth.com/mod/re-ftbqkeys ）

好的，这并不难实现
后面会加上，你可以关注一下后续的更新

**Comment by XDawned** [comment]
已更新

**Comment by KlparetlR** [comment]
多谢拉

**Comment by KlparetlR** [comment]
but

**Comment by KlparetlR** [comment]
![截图20230315202607](https://user-images.githubusercontent.com/105189905/225308533-d76ebfe2-59d7-4df4-973e-0886d55d89f8.png)
func文件夹里没有这个功能文件

**Comment by XDawned** [comment]
已添加

**Comment by KlparetlR** [comment]
没有报错了，谢谢啦

**Comment by KlparetlR** [comment]
看到你有想法接入chatGPT，现在已经有这针对gal的产品出现，不知道对你有没有帮助：
https://www.bilibili.com/video/BV1YN411w7mt/
https://github.com/Lilyltt/GalUpTs/releases/tag/GalUpTs1.0.0
https://github.com/sashabaranov/go-openai

**Comment by XDawned** [comment]
感谢您的提议

其实还有一个难点，国内chatgpt的api其实并不方便申请（~~而且chatgpt的api接口是没法白嫖的~~）

替代品的话我有简单训练过一个针对MC专业名词的翻译模型[minecraft-modpack-quests-transformer](https://huggingface.co/XDawned/minecraft-modpack-quests-transformer)来规避诸如‘暴徒’,‘产卵期’之类的典型机翻，同时对诸如植物魔法、通用机械、学魔法等的模组物品名词进行了优化。
此项目的分支[model_trans](https://github.com/XDawned/FTBQLocalizationTools/tree/model_trans)
中使用的正是这个模型，但是由于涉及到机器学习，依赖的第三方库很多，所以我并没有将它放入主分支中，如果感兴趣的话你可以尝试克隆此分支，它不依赖外部翻译api，运行后会自行下载机翻模型并运行
![image](https://user-images.githubusercontent.com/96915192/230836210-918e30ff-ff44-4b7b-9919-6afb4c661e1e.png)

**Comment by KlparetlR** [comment]
我有机会再尝试，现在在准备比赛

**Comment by XDawned** [comment]
内嵌了机器学习翻译模型的版本已经完成打包，无需外部付费翻译API [下载地址](https://pan.baidu.com/s/1sTkahnteb_abiM27r1LCxw?pwd=v4np)
[模型](https://huggingface.co/XDawned/minecraft-modpack-quests-transformer)训练集提取自人工精品汉化任务文件，但数量级还达不到要求，目前已经可以做到正确翻译原版和诸如血魔法、通用机械等整合包任务中提及较多的术语..
