### ISSUE TITLE
任务的外链翻译错误

### ISSUE THREAD

**Issue by Holy-Fak** [XDawned/FTBQLocalizationTools#5]
![image](https://user-images.githubusercontent.com/63405709/228433150-a02bab14-ea20-4fc1-8d6e-db8540108b76.png)

任务原文discription长这样
![image](https://user-images.githubusercontent.com/63405709/228435288-05b96e14-b149-4a6c-a23d-41157dca4a9a.png)

Quest from modpack: Engimatica 9
感觉这样写超链接属实有点骚

**Comment by XDawned** [comment]
> ![image](https://user-images.githubusercontent.com/63405709/228433150-a02bab14-ea20-4fc1-8d6e-db8540108b76.png)
> 
> 任务原文discription长这样 ![image](https://user-images.githubusercontent.com/63405709/228435288-05b96e14-b149-4a6c-a23d-41157dca4a9a.png)
> 
> Quest from modpack: Engimatica 9 感觉这样写超链接属实有点骚

感谢反馈，项目已更新，你可以更新项目再次使用。
- 由于这种格式并不常见，凡是含有超链接的整行文本都将不再被翻译，如果行内存在其它需要翻译的内容您可以选择手动汉化。
- 由于你并没有提供snbt文件，我无法100%还原报错情境，如果更新后问题仍然存在希望可以采用[pastebin](https://pastebin.ubuntu.com/)或其它形式将snbt文件反馈给我。

**Comment by Holy-Fak** [comment]
（神速更新的作者好耶！）
目前来看他正确工作了

下面是这坨任务的原文
https://pastebin.com/NvQbG5Ka
