### ISSUE TITLE
lang文件提取不完善。

### ISSUE THREAD

**Issue by Pasuu** [XDawned/FTBQLocalizationTools#6]
你可以复制这段任务[create](https://mclo.gs/fT6aep7)，进行提取，他只能提取第一段title内容。

**Comment by XDawned** [comment]
感谢反馈，
## 问题源头
由于FTB官方并没有提供除了游戏内置snbt解析之外的其它解析方式，所以此项目使用了[Tryanks](https://github.com/Tryanks)提供的[python-snbtlib](https://github.com/Tryanks/python-snbtlib)

然而此解析库目前还在初期阶段，在处理格式不标准的snbt文件时会产生解析错误。

比如你所提供的任务解析错误位置之一为
`icon: { id: "create:large_cogwheel", Count: 2b }`
标准情况下应该写成
![image](https://user-images.githubusercontent.com/96915192/231350346-53c6848e-ffe4-499f-a47c-a2bdbcb0fc29.png)
## 解决方案
- 手动将不标准的格式进行修正，比如你所提供这份snbt文件共有类似上面我提到的未分行类型的两处不标准，我在手动修正并且成功进行了提取  [修正后文件](https://pastebin.ubuntu.com/p/SCY59tvZ3w/)，脚本是可以正常执行提取的。
- 先前我已经向解析库作者提交了关于这个问题的issue，造轮子并不简单，所以最终的修正还需要耐心等待解析库作者的更新，日后解析库如果更新并解决了不标准格式读取使用`pip install --upgrade snbtlib`即可解决上述问题。

**Comment by Tryanks** [comment]
感谢@XDawned 的pull request，问题已修复
