### ISSUE TITLE
[问题] 翻译lang文件生成的zh_cn.json文件

### ISSUE THREAD

**Issue by xukai19941231** [XDawned/FTBQLocalizationTools#7]
```
// config.json 配置 
{
  "QUESTS_PATH" : "./_temp/ftbquests",
  "LANG_PATH" : "./_temp/en_us.json",
  "KEEP_ORIGINAL" : true,
  "BACK_FILL_PATH" : "./_temp/ftbquests-trans",
  "BACK_FILL_LANG_PATH" : "./_temp/zh_cn.json"
}
```

本地工具路径：F:\FTBQ本地化小工具(beta)\FTBQ本地化工具\
en_us.json放置路径：F:\FTBQ本地化小工具(beta)\FTBQ本地化工具\_temp\

打开工具并选择主导功能 - 3.翻译lang文件
翻译后生成的文件在根目录下面有个zh_cn.json的"文件夹"，里面是个en_us.json文件，打开确定了是翻译后的文件。
但这个路径既不是配置中的_temp路径，也不是en_us.json的同级目录下，文件名字也有误。

**Comment by xukai19941231** [comment]
系统：Windows 11 专业版
版本：22H2 - 22621.1555

**Comment by XDawned** [comment]
感谢反馈
这是由于我在编写时输出路径生成方法错误导致的，理论上只会影响功能3和功能4
你在使用其余几个功能时是否也遇到了这些问题？

**Comment by XDawned** [comment]
这个问题算不上致命，或许可以先用着这一版

后面将会在Tryanks大佬修复[snbtlib数字键值无法识别](https://github.com/Tryanks/python-snbtlib/issues/5)
后在releases中上传新的打包版本一并解决这些问题

_PS:snbtlib可能需要参考FTBQ官方的源码重构整个读取逻辑，毕竟缝缝补补不是长久之策，可能需要一小段时间...._

**Comment by xukai19941231** [comment]
> 感谢反馈 这是由于我在编写时输出路径生成方法错误导致的，理论上只会影响功能3和功能4 你在使用其余几个功能时是否也遇到了这些问题？

使用其他功能没遇到这种问题，只是怕你没注意到这个问题，所以才来GitHub提一下。加油，工具很好用。

**Comment by XDawned** [comment]
v1.2版本已修复
