### ISSUE TITLE
本地版打包文件使用出现ssl错误

### ISSUE THREAD

**Issue by Orisland** [XDawned/FTBQLocalizationTools#8]
如题，
我尝试开梯子，关梯子，全局模式，tun模式，全部无效。
我没有发现config文件中存在proxy参数。

https://pste.ch/amusucozer.rb

config
```java
{
  "QUESTS_PATH" : "D:\Game\MC\translate\AOF6\QUEST_PATH\ftbquests",
  "LANG_PATH" : "D:\Game\MC\translate\AOF6\LANG_PATH\en_us.json",
  "KEEP_ORIGINAL" : true,
  "BACK_FILL_PATH" : "D:\Game\MC\translate\AOF6\BACK_FILL_PATH",
  "BACK_FILL_LANG_PATH" : "D:\Game\MC\translate\AOF6\LANG_PATH\zh_cn.json"
}
```
![image](https://github.com/XDawned/FTBQLocalizationTools/assets/59354152/6c165a3d-96b4-4b50-841e-f319a6b516f9)
我确认我已经把quest文件放入了这个文件夹。
是我的配置有问题吗？

**Comment by XDawned** [comment]
今天下午模型更新添加了safetensors，程序每次启动前会连接hugging-face平台检查模型是否需要更新，一般国内直接连接即可，使用加速反而可能导致443网络连接错误。

你可以等待一段时间后重试，或者尝试换个网络环境，比如使用手机热点之类的。

访问[hugging-face](https://huggingface.co/XDawned/minecraft-en-zh)可以测试基础连接是否通畅

**Comment by Orisland** [comment]
我确认该网站我可以在不启动梯子的情况下进行访问，但在程序中仍出现这个错误。
![image](https://github.com/XDawned/FTBQLocalizationTools/assets/59354152/443fefbc-a6a7-43ab-be36-75d986f80865)
而错误似乎也出现了其他的
https://pste.ch/kukuqaseru.rb

**Comment by Orisland** [comment]
我通过clone整个项目在pycharm里跑任务似乎会卡在一个奇怪的地方。
![image](https://github.com/XDawned/FTBQLocalizationTools/assets/59354152/bd40e323-3f09-466b-805d-1cb148e5a4ae)
错误日志，会完全卡在位置不会再继续翻译
https://pste.ch/xasanoyawo.sql

附上
翻译卡住的文件
[ad_astra.zip](https://github.com/XDawned/FTBQLocalizationTools/files/11704287/ad_astra.zip)

后注：
？？
我debug加了一条判断内容的代码怎么就能过去了？
![image](https://github.com/XDawned/FTBQLocalizationTools/assets/59354152/a7502011-a60e-4c40-b847-ff47a950c6ef)

**Comment by XDawned** [comment]
应该还是因为网络的原因，模型调用阶段会出现各种缺失或者connection错误，近期hugging-face的国内直连越来越不稳定，下个版本会去掉校验
main分支的百度API翻译是没有出现错误的，一直没有合并full版本也是出于这个考虑

**Comment by XDawned** [comment]
基于此项目开发的新项目已发布，兼具大部分功能
由于项目整体变动较大，所以另开新库
[ModpackLocalizationTools](https://github.com/XDawned/ModpackLocalizationTools)
