### ISSUE TITLE
使用时出错，闪退。 疯狂截图截到的是这样的错误

### ISSUE THREAD

**Issue by jacksixth** [XDawned/FTBQLocalizationTools#9]
![image](https://github.com/XDawned/FTBQLocalizationTools/assets/42532036/85cbdc61-7b36-4f84-8e18-b88578016e42)

**Comment by XDawned** [comment]
感谢反馈

与 #8 相同，出现ConnectionResetError与离线模型托管站点网络不稳定有关
目前可以暂时使用精简版，采用[百度翻译API](http://api.fanyi.baidu.com/)作为翻译源

后面我会尝试在新版本修复，在修复后我才会关闭此Issue，届时您可以收到通知。

**Comment by jacksixth** [comment]
好的 谢谢

**Comment by XDawned** [comment]
解决方案见 #8 最新评论
